#!/bin/bash

version="1.1"

function menu
{
	clear
	
	echo
	echo -e "\e[39m  __  __   ______    _____ "
	echo -e " |  \/  | |  ____|  / ____|"
	echo -e " | \  / | | |__    | |     "
	echo -e " | |\/| | |  __|   | |     "
	echo -e " | |  | | | |      | |____ "
	echo -e " |_|  |_| |_|       \_____|"
	echo -e "                           "
	echo -e "              \e[90mby LYSYyy $version\e[0m"
	echo
	echo -e " \e[1;33m+Metasploit Fast Connect+\e[0m"
	echo 
	echo -e " \e[1m1\e[21m. Add a new connection"
	echo -e " \e[1m2\e[21m. Connections"
	echo -e " \e[1m3\e[21m. Parameters"
	echo
	echo -e " \e[1;31m0\e[21;39m. Exit"
	echo
	echo -ne "\e[1;31mMFC\e[21;39m:~# "
	read -e option

	if [ $option = 1 ]; then
		function new_connect
		{
			clear
			echo
			echo -e "\e[39m  __  __   ______    _____ "
			echo -e " |  \/  | |  ____|  / ____|"
			echo -e " | \  / | | |__    | |     "
			echo -e " | |\/| | |  __|   | |     "
			echo -e " | |  | | | |      | |____ "
			echo -e " |_|  |_| |_|       \_____|"
			echo -e "                           "
			echo -e "              \e[90mby LYSYyy $version\e[0m"
			echo
			echo -e " \e[1;33m+Metasploit Fast Connect+\e[0m"
			echo
			echo -ne "\e[21;39mPlease enter name of the connection:\e[1;39m "
			read -e name
			echo -ne "\e[21;39mPlease enter PAYLOAD:\e[1;39m "
			read -e payload
			echo -ne "\e[21;39mPlease enter LHOST:\e[1;39m "
			read -e lhost
			echo -ne "\e[21;39mPlease enter LPORT:\e[1;39m "
			read -e lport
			echo
			echo -e " \e[1;32m[+]\e[1;39m Starting creating a new connection...\e[21;90m"
			
			touch ~/.mfconnect/$name.rc
			echo use exploit/multi/handler > ~/.mfconnect/$name.rc
			echo set PAYLOAD $payload >> ~/.mfconnect/$name.rc
			echo set LHOST $lhost >> ~/.mfconnect/$name.rc
			echo set LPORT $lport >> ~/.mfconnect/$name.rc
			echo set ExitOnSession false >> ~/.mfconnect/$name.rc
			echo exploit -j >> ~/.mfconnect/$name.rc
			
			if [ -e ~/.mfconnect/$name.rc ]; then
				echo
				echo -e "\e[1;32mNew connection has been create!\e[0m"
				echo
				read
				menu
			
			else
				clear
				echo
				echo -e "\e[1;31mError!\e[0m"
				echo
				read
				menu
			fi
		}
		
		new_connect
		
	elif [ $option = 2 ]; then
		
		function list
		{
			clear
			echo
			echo -e "\e[1m----------------------------\e[1;32m"
			echo
			cd ~/.mfconnect
			find *
			echo
			echo -e "\e[1;39m----------------------------\e[0m"
			echo
			echo -e " \e[1;33m+Metasploit Fast Connect+\e[0m"
			echo 
			echo -e " \e[1m1\e[21m. Connect"
			echo -e " \e[1m2\e[21m. Edit"
			echo -e " \e[1m3\e[21m. Rename"
			echo -e " \e[1m4\e[21m. Delete"
			echo
			echo -e " \e[1m0\e[21m. Back"
			echo
			echo -ne "\e[1;31mMFC\e[21;39m:~# "
			read -e option
			
			if [ $option = 1 ]; then
				echo
				echo -ne "\e[1;96m[CONNECT]\e[21;39m Please enter name of the connection (\e[31mless .rc\e[39m):\e[1m "
				read -e name
				clear
				echo
				echo -e " \e[1;32m[+]\e[1;39m Starting connection..."
				echo
				msfconsole -q -r ~/.mfconnect/$name.rc
				list
				
			elif [ $option = 2 ]; then
				echo
				echo -ne "\e[1;32m[EDIT]\e[21;39m Please enter name of the connection (\e[31mless .rc\e[39m):\e[1m "
				read -e name
				echo
				nano ~/.mfconnect/$name.rc
				list
				
			elif [ $option = 3 ]; then
				echo
				echo -ne "\e[1;33m[RENAME]\e[21;39m Please enter \e[1;39mOLD\e[21;39m connect name (\e[31mless .rc\e[39m):\e[1m "
				read -e name
				echo -ne "\e[1;33m[RENAME]\e[21;39m Please enter \e[1;39mNEW\e[21;39m connect name (\e[31mless .rc\e[39m):\e[1m "
				read -e newname
				echo
				mv ~/.mfconnect/$name.rc ~/.mfconnect/$newname.rc
				list
				
			elif [ $option = 4 ]; then
				echo
				echo -ne "\e[1;31m[DELETE]\e[21;39m Please enter name of the connection (\e[31mless .rc\e[39m):\e[1m "
				read -e name
				echo
				rm ~/.mfconnect/$name.rc
				list
				
			elif [ $option = 0 ]; then
				menu
				
			else
				clear
				echo
				echo -e "\e[1;31mSelected wrong options!\e[0m"
				echo
				read
				list
				
			fi
		}
		
		list
		
	elif [ $option = 3 ]; then
		clear
		echo
		echo -e "\e[39m  __  __   ______    _____ "
		echo -e " |  \/  | |  ____|  / ____|"
		echo -e " | \  / | | |__    | |     "
		echo -e " | |\/| | |  __|   | |     "
		echo -e " | |  | | | |      | |____ "
		echo -e " |_|  |_| |_|       \_____|"
		echo -e "                           "
		echo -e "              \e[90mby LYSYyy $version\e[0m"
		echo
		echo -e " \e[1;33m+Metasploit Fast Connect+\e[0m"
		echo
		echo -e "\e[1;39mMFC allows you to use parameters for more efficient and faster connection management:\e[0m"
		echo
		echo -e " \e[1;39mmfc -c [CONNECT NAME]\e[21;37m - Fast connection"
		echo -e " \e[1;39mmfc -rm [CONNECT NAME]\e[21;37m - Delete the selected connection"
		echo -e " \e[1;39mmfc -edit [CONNECT NAME]\e[21;37m - Fast modification of the selected connection"
		echo -e " \e[1;39mmfc -ls\e[21;37m - Connect list"
		echo -e " \e[1;39mmfc -uninstall\e[21;37m - Uninstall MFC"
		echo
		read
		menu
		
	elif [ $option = 0 ]; then
		clear
		echo
		echo -e "\e[1;33mGood Bye :)\e[0m"
		echo
		exit
		
	else
		clear
		echo
		echo -e "\e[1;31mSelected wrong options!\e[0m"
		echo
		read
		menu
	fi
}

menu
