#!/bin/bash

version="1.1"

function menu
{
	clear
	
	echo
	echo -e "\e[39;24m  __  __   ______    _____ "
	echo -e " |  \/  | |  ____|  / ____|"
	echo -e " | \  / | | |__    | |     "
	echo -e " | |\/| | |  __|   | |     "
	echo -e " | |  | | | |      | |____ "
	echo -e " |_|  |_| |_|       \_____|"
	echo -e "                           "
	echo -e "              \e[90;24mby LYSYyy $version\e[0m"
	echo
	echo -e " \e[1;33;24m+Metasploit Fast Connect+\e[0m"
	echo 
	echo -e " \e[1;24m1\e[21;24m. Dodaj nowe polaczenie"
	echo -e " \e[1;24m2\e[21;24m. Polaczenia"
	echo -e " \e[1;24m3\e[21;24m. Parametry"
	echo
	echo -e " \e[1;31;24m0\e[21;39;24m. Wyjscie"
	echo
	echo -ne "\e[1;31;24mMFC\e[21;39;24m:~# "
	read -e opcja

	if [ $opcja = 1 ]; then
		function nowe_polaczenie
		{
			clear
			echo
			echo -e "\e[39;24m  __  __   ______    _____ "
			echo -e " |  \/  | |  ____|  / ____|"
			echo -e " | \  / | | |__    | |     "
			echo -e " | |\/| | |  __|   | |     "
			echo -e " | |  | | | |      | |____ "
			echo -e " |_|  |_| |_|       \_____|"
			echo -e "                           "
			echo -e "              \e[90;24mby LYSYyy $version\e[0m"
			echo
			echo -e " \e[1;33;24m+Metasploit Fast Connect+\e[0m"
			echo
			echo -ne "\e[21;39;24mProsze podac nazwe polaczenia:\e[1;39;24m "
			read -e nazwa
			echo -ne "\e[21;39;24mProsze podac PAYLOAD:\e[1;39;24m "
			read -e payload
			echo -ne "\e[21;39;24mProsze podac LHOST:\e[1;39;24m "
			read -e lhost
			echo -ne "\e[21;39;24mProsze podac LPORT:\e[1;39;24m "
			read -e lport
			echo
			echo -e " \e[1;32;24m[+]\e[1;39;24m Rozpoczynam tworzenie nowego polaczenia...\e[21;90;24m"
			
			touch ~/.mfconnect/$nazwa.rc
			echo use exploit/multi/handler > ~/.mfconnect/$nazwa.rc
			echo set PAYLOAD $payload >> ~/.mfconnect/$nazwa.rc
			echo set LHOST $lhost >> ~/.mfconnect/$nazwa.rc
			echo set LPORT $lport >> ~/.mfconnect/$nazwa.rc
			echo set ExitOnSession false >> ~/.mfconnect/$nazwa.rc
			echo exploit -j >> ~/.mfconnect/$nazwa.rc
			
			if [ -e ~/.mfconnect/$nazwa.rc ]; then
				echo
				echo -e "\e[1;32;24mNowe polaczenie zostalo utworzone!\e[0m"
				echo
				read
				menu
			
			else
				clear
				echo
				echo -e "\e[1;31;24mDoszlo do bledu!\e[0m"
				echo
				read
				menu
			fi
		}
		
		nowe_polaczenie
		
	elif [ $opcja = 2 ]; then
		
		function lista
		{
			clear
			echo
			echo -e "\e[1;24m----------------------------\e[1;32;24m"
			echo
			cd ~/.mfconnect
			find *
			echo
			echo -e "\e[1;39;24m----------------------------\e[0m"
			echo
			echo -e " \e[1;33;24m+Metasploit Fast Connect+\e[0m"
			echo 
			echo -e " \e[1;24m1\e[21;24m. Polacz"
			echo -e " \e[1;24m2\e[21;24m. Edytuj"
			echo -e " \e[1;24m3\e[21;24m. Zmien nazwe"
			echo -e " \e[1;24m4\e[21;24m. Usun"
			echo
			echo -e " \e[1;24m0\e[21;24m. Menu"
			echo
			echo -ne "\e[1;31;24mMFC\e[21;39;24m:~# "
			read -e opcja
			
			if [ $opcja = 1 ]; then
				echo
				echo -ne "\e[1;96;24m[POLACZ]\e[21;39;24m Prosze podac nazwe polaczenia (\e[31;24mbez .rc\e[39;24m):\e[1;24m "
				read -e nazwa
				clear
				echo
				echo -e " \e[1;32;24m[+]\e[1;39;24m Rozpoczynam polaczenie..."
				echo
				msfconsole -q -r ~/.mfconnect/$nazwa.rc
				lista
				
			elif [ $opcja = 2 ]; then
				echo
				echo -ne "\e[1;32;24m[EDYTUJ]\e[21;39;24m Prosze podac nazwe polaczenia (\e[31;24mbez .rc\e[39;24m):\e[1;24m "
				read -e nazwa
				echo
				nano ~/.mfconnect/$nazwa.rc
				lista
				
			elif [ $opcja = 3 ]; then
				echo
				echo -ne "\e[1;33;24m[ZMIEN NAZWE]\e[21;39;24m Prosze podac \e[1;39;24mSTARA\e[21;39;24m nazwe polaczenia (\e[31mbez .rc\e[39m;24):\e[1;24m "
				read -e nazwa
				echo -ne "\e[1;33;24m[ZMIEN NAZWE]\e[21;39;24m Prosze podac \e[1;39;24mNOWA\e[21;39;24m nazwe polaczenia (\e[31;24mbez .rc\e[39;24):\e[1;24m "
				read -e newnazwa
				echo
				mv ~/.mfconnect/$nazwa.rc ~/.mfconnect/$newnazwa.rc
				lista
				
			elif [ $opcja = 4 ]; then
				echo
				echo -ne "\e[1;31;24m[USUN]\e[21;39;24m Prosze podac nazwe polaczenia (\e[31;24mbez .rc\e[39;24m):\e[1;24m "
				read -e nazwa
				echo
				rm ~/.mfconnect/$nazwa.rc
				lista
				
			elif [ $opcja = 0 ]; then
				menu
				
			else
				clear
				echo
				echo -e "\e[1;31;24mWybrano nieprawidlowa opcje!\e[0m"
				echo
				read
				lista
				
			fi
		}
		
		lista
		
	elif [ $opcja = 3 ]; then
		clear
		echo
		echo -e "\e[39;24m  __  __   ______    _____ "
		echo -e " |  \/  | |  ____|  / ____|"
		echo -e " | \  / | | |__    | |     "
		echo -e " | |\/| | |  __|   | |     "
		echo -e " | |  | | | |      | |____ "
		echo -e " |_|  |_| |_|       \_____|"
		echo -e "                           "
		echo -e "              \e[90;24mby LYSYyy $version\e[0m"
		echo
		echo -e " \e[1;33;24m+Metasploit Fast Connect+\e[0m"
		echo
		echo -e "\e[1;39;24mMFC umozliwia wykorzystywanie parametrow do wydajniejszego i szybszego zarzadzania polaczeniami:\e[0m"
		echo
		echo -e " \e[1;39;24mmfc -c [NAZWA POLACZENIA]\e[21;37;24m - Szybkie polaczenie"
		echo -e " \e[1;39m;24mfc -rm [NAZWA POLACZENIA]\e[21;37;24m - Usuwanie wybranego polaczenia"
		echo -e " \e[1;39;24mmfc -edit [NAZWA POLACZENIA]\e[21;37;24m - Szybka modyfikacja wybranego polaczenia"
		echo -e " \e[1;39;24mmfc -ls\e[21;37;24m - Lista polaczen"
		echo -e " \e[1;39;24mmfc -uninstall\e[21;37;24m - Usuwanie MFC"
		echo
		read
		menu
		
	elif [ $opcja = 0 ]; then
		clear
		echo
		echo -e "\e[1;33;24mDo zobaczenia :)\e[0m"
		echo
		exit
		
	else
		clear
		echo
		echo -e "\e[1;31;24mWybrano nieprawidlowa opcje!\e[0m"
		echo
		read
		menu
	fi
}

menu
