#!/bin/bash

version="1.0"

	clear
	
	echo "PL"
	echo -e "  __  __   ______    _____ "
	echo -e " |  \/  | |  ____|  / ____|"
	echo -e " | \  / | | |__    | |     "
	echo -e " | |\/| | |  __|   | |     "
	echo -e " | |  | | | |      | |____ "
	echo -e " |_|  |_| |_|       \_____|"
	echo -e "                           "
	echo -e "              \e[90mby LYSYyy $version\e[0m"
	echo
	echo -e " \e[1;33m+Metasploit Fast Connect+\e[0m"
	
		echo
		echo -e " \e[1;32m[+]\e[1;39m Rozpoczynam instalacje...\e[21;90m"
		echo
		
		apt-get update
		apt-get install nano
		mkdir ~/.mfconnect
		clear
		
		echo
		echo -e "\e[1;32mInstalacja zakonczona!\e[0m"
		echo
		
		sleep 1
		
		source mfc
